apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-policy.yaml
  - redis-policy.yaml
  - mercure-policy.yaml
  - backend-policy.yaml
  - frontend-policy.yaml
  # Include default-deny.yaml only if you're ready to enforce strict policies
  # - default-deny.yaml