framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'

        pools:
            # Default app cache pool
            app.cache:
                adapter: cache.adapter.redis
                default_lifetime: 3600 # 1 hour default TTL

            # Dedicated pool for API responses
            api_response.cache:
                adapter: cache.adapter.redis
                default_lifetime: 600 # 10 minute TTL

            # Dedicated pool for user data
            user_data.cache:
                adapter: cache.adapter.redis
                default_lifetime: 1800 # 30 minute TTL
