nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        expose_headers: ['Link', 'Content-Disposition']
        max_age: 3600
    paths:
        '^/api/auth/google/callback': # Ensure this path is allowed
            allow_origin: [ 'http://localhost:3030' ]
            allow_headers: [ 'Content-Type', 'Authorization' ]
            allow_methods: [ 'GET', 'OPTIONS' ]
        '^/': null
