apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
        - name: nextjs
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "https://api-staging.example.com"
            - name: NEXT_PUBLIC_MERCURE_HUB_URL
              value: "https://mercure-staging.example.com/.well-known/mercure"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  template:
    spec:
      containers:
        - name: php-fpm
          env:
            - name: APP_ENV
              value: "staging"
            - name: MERCURE_URL
              value: "http://mercure:80/.well-known/mercure"
            - name: MERCURE_PUBLIC_URL
              value: "https://mercure-staging.example.com/.well-known/mercure"