apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-kubernetes-auth
  namespace: vault
data:
  backend-role.json: |
    {
      "bound_service_account_names": ["backend-sa"],
      "bound_service_account_namespaces": ["chat-app"],
      "policies": ["chat-app-backend"],
      "ttl": "1h"
    }
  frontend-role.json: |
    {
      "bound_service_account_names": ["frontend-sa"],
      "bound_service_account_namespaces": ["chat-app"],
      "policies": ["chat-app-frontend"],
      "ttl": "1h"
    }