apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-secrets-config
  namespace: vault
data:
  backend-secrets.json: |
    {
      "data": {
        "app_secret": "your-app-secret",
        "database_url": "postgresql://app:strong-password@postgres:5432/app?serverVersion=16&charset=utf8",
        "mercure_jwt_secret": "your-mercure-jwt-secret",
        "jwt_passphrase": "your-jwt-passphrase"
      }
    }
  frontend-secrets.json: |
    {
      "data": {
        "google_client_id": "your-google-client-id",
        "google_client_secret": "your-google-client-secret"
      }
    }
  config-values.json: |
    {
      "data": {
        "app_env": "prod",
        "mercure_url": "https://mercure.your-domain.com/.well-known/mercure",
        "mercure_public_url": "https://mercure.your-domain.com/.well-known/mercure",
        "redis_url": "redis://redis:6379",
        "redis_chat_ttl": "604800",
        "next_public_api_url": "https://api.your-domain.com",
        "next_public_mercure_hub_url": "https://mercure.your-domain.com/.well-known/mercure"
      }
    }