apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
  labels:
    app: chat-app
    component: proxy
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-app
      component: proxy
  template:
    metadata:
      labels:
        app: chat-app
        component: proxy
        tier: frontend
    spec:
      serviceAccountName: caddy-sa
      containers:
        - name: caddy
          image: ghcr.io/skunac/chat-project--caddy:latest
          ports:
            - containerPort: 80
            - containerPort: 443
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20