apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: chat-app
  labels:
    app: chat-app
    component: frontend
    tier: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-app
      component: frontend
  template:
    metadata:
      labels:
        app: chat-app
        component: frontend
        tier: application
    spec:
      serviceAccountName: frontend
      containers:
        - name: nextjs
          image: ghcr.io/skunac/chat-project--frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: NEXT_PUBLIC_API_URL
              value: "http://api.local.com"
            - name: NEXT_PUBLIC_MERCURE_HUB_URL
              value: "http://mercure.local.com/.well-known/mercure"
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: google-client-id
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: google-client-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20
