apiVersion: apps/v1
kind: Deployment
metadata:
  name: mercure
  namespace: chat-app
  labels:
    app: chat-app
    component: mercure
    tier: messaging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-app
      component: mercure
  template:
    metadata:
      labels:
        app: chat-app
        component: mercure
        tier: messaging
    spec:
      serviceAccountName: mercure
      containers:
        - name: mercure
          image: dunglas/mercure
          ports:
            - containerPort: 80
          env:
            - name: SERVER_NAME
              value: ":80"
            - name: MERCURE_PUBLISHER_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: mercure-jwt-secret
            - name: MERCURE_SUBSCRIBER_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: mercure-jwt-secret
            - name: CORS_ALLOWED_ORIGINS
              value: "*"
            - name: MERCURE_EXTRA_DIRECTIVES
              value: |
                cors_origins *
                anonymous
                subscriptions
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
