apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: chat-app
  labels:
    app: chat-app
    component: cache
    tier: data
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: chat-app
      component: cache
  template:
    metadata:
      labels:
        app: chat-app
        component: cache
        tier: data
    spec:
      containers:
        - name: redis
          image: redis:alpine
          command: ["redis-server", "--appendonly", "yes"]
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
