apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployments/backend.yaml
  - deployments/frontend.yaml
  - deployments/caddy.yaml
  - deployments/mercure.yaml
  - deployments/postgres.yaml
  - deployments/redis.yaml
  - services/backend-svc.yaml
  - services/frontend-svc.yaml
  - services/mercure-svc.yaml
  - services/postgres-svc.yaml
  - services/redis-svc.yaml
  - storage/postgres-pvc.yaml
  - storage/redis-pvc.yaml
  - service-accounts/backend-sa.yaml
  - service-accounts/frontend-sa.yaml
  - service-accounts/mercure-sa.yaml
  - ingress/chat-app-ingress.yaml
  - config/app-config.yaml
  - namespace.yaml