apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployments/backend.yaml
  - deployments/frontend.yaml
  - deployments/mercure.yaml
  - deployments/postgres.yaml
  - deployments/redis.yaml
  - services/backend-svc.yaml
  - services/frontend-svc.yaml
  - services/mercure-svc.yaml
  - services/postgres-svc.yaml
  - services/redis-svc.yaml
  - ingress/chat-app-ingress.yaml
  - security/security-context.yaml
