apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chat-app-staging

resources:
  - ../../base

# Replace the namespace in all resources
namePrefix: staging-

# Add environment-specific labels
commonLabels:
  environment: staging

# Configure replicas for staging
patches:
  - path: patches/replicas-staging.yaml
  - path: patches/resources-staging.yaml
  - path: patches/ingress-staging.yaml
  - path: patches/config-staging.yaml

# Define ConfigMap with staging-specific values
configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - APP_ENV=staging
      - CORS_ALLOW_ORIGIN=^https?://(staging\.example\.com)(:[0-9]+)?$