apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: chat-app
spec:
  selector:
    app: chat-app
    component: backend
  ports:
    - name: fpm
      port: 9000
      targetPort: 9000
