apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: chat-app
spec:
  selector:
    app: chat-app
    component: frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
