apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: chat-app
spec:
  selector:
    app: chat-app
    component: database
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  clusterIP: None
