apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: chat-app
spec:
  selector:
    app: chat-app
    component: cache
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  clusterIP: None
