apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: chat-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: chat-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mercure
  namespace: chat-app
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: chat-app
type: Opaque
stringData:
  database-url: "postgresql://app:YOUR_PASSWORD@postgres:5432/app?serverVersion=16&charset=utf8"
  app-secret: "YOUR_APP_SECRET"
  mercure-jwt-secret: "YOUR_MERCURE_JWT_SECRET"
  jwt-passphrase: "YOUR_JWT_PASSPHRASE"
  google-client-id: "YOUR_GOOGLE_CLIENT_ID"
  google-client-secret: "YOUR_GOOGLE_CLIENT_SECRET"
  postgres-password: "YOUR_POSTGRES_PASSWORD"
