apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chat-app-prod

resources:
  - ../../base
  - hpa/backend-hpa.yaml
  - hpa/frontend-hpa.yaml
  - pdb/backend-pdb.yaml
  - pdb/frontend-pdb.yaml

# No namePrefix for production (clean URLs)

# Add environment-specific labels
commonLabels:
  environment: production

# Configure production-specific settings
patches:
  - path: patches/replicas-prod.yaml
  - path: patches/resources-prod.yaml
  - path: patches/ingress-prod.yaml
  - path: patches/config-prod.yaml
  - path: patches/security-context.yaml

# Define ConfigMap with production-specific values
configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - APP_ENV=prod
      - CORS_ALLOW_ORIGIN=^https?://(chat\.example\.com|api\.example\.com|mercure\.example\.com)(:[0-9]+)?$