apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chat-app-dev

resources:
  - ../../base

# Replace the namespace in all resources
namePrefix: dev-

# Add environment-specific labels
labels:
  - pairs:
      environment: development

# Configure replicas for development (fewer resources)
patches:
  - path: patches/replicas-dev.yaml
  - path: patches/resources-dev.yaml
  - path: patches/ingress-dev.yaml
  - path: patches/config-dev.yaml

# Define ConfigMap with development-specific values
configMapGenerator:
  - name: dev-app-config
    literals:
      - APP_ENV=dev
      - CORS_ALLOW_ORIGIN=^https?://(localhost|127\.0\.0\.1|chat-dev\.example\.com)(:[0-9]+)?$